# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 07 Mar 2016 02:08:51 +0000
*               @ALL          1
*               @user         8
