<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 07 Mar 2016 05:53:31 +0100
 */

$conf['title'] = 'DokuWiki ';
$conf['lang'] = 'zh';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'qingzi.wang@cq-tct.com';
$conf['proxy']['pass'] = '<b>MTIzNDU2';

// end auto-generated content
